!GLXLIB.CTL
!This control file creates EXE and REL version of GLXLIB

!                        COPYRIGHT (C) 1984,1987,1988
!                    DIGITAL EQUIPMENT CORPORATION

!System Files

!	LINK.EXE
!	MACRO.EXE

@SET TRAP FILE

!Required Files in Your Area

!	GALCNF.MAC	GALAXY Configuration File
!	ORNMAC.UNV

!Source Files

!	GLXVER.MAC
!	GLXMAC.MAC
!	GLXINI.MAC
!	GLXOTS.MAC
!	GLXCOM.MAC
!	GLXIPC.MAC
!	GLXFIL.MAC
!	GLXTXT.MAC
!	GLXLNK.MAC
!	GLXSCN.MAC
!	GLXKBD.MAC
!	GLXMEM.MAC
!	GLXINT.MAC

!Output Files

!	GLXMAC.UNV
!	GLXMAC.L36
!	GLXINI.REL
!	GLXLIB.REL
!	GLXLIB.EXE

@TAKE BATCH.CMD

@DEF REL: DSK:,REL:
@DEF UNV: DSK:,UNV:

@VDIR	GLXMAC.MAC
@VDIR	GLXINI.MAC
@VDIR	GLXOTS.MAC
@VDIR	GLXCOM.MAC
@VDIR	GLXIPC.MAC
@VDIR	GLXFIL.MAC
@VDIR	GLXTXT.MAC
@VDIR	GLXLNK.MAC
@VDIR	GLXSCN.MAC
@VDIR	GLXKBD.MAC
@VDIR	GLXMEM.MAC
@VDIR	GLXINT.MAC

!Create GALAXY configuration universal
@COMPILE/COMPILE GALCNF.MAC

;
; Build GLXLIB linkable library
;

@COPY TTY: GLXPUR.MAC
@GLXPURE==0
@

@COMPILE /COMPILE GLXPUR.MAC+GLXMAC.MAC
@COMPILE /COMPILE GLXINI.MAC
@COMPILE /COMPILE GLXCOM.MAC
@COMPILE /COMPILE GLXFIL.MAC
@COMPILE /COMPILE GLXINT.MAC
@COMPILE /COMPILE GLXIPC.MAC
@COMPILE /COMPILE GLXKBD.MAC
@COMPILE /COMPILE GLXLNK.MAC
@COMPILE /COMPILE GLXMEM.MAC
@COMPILE /COMPILE GLXOTS.MAC
@COMPILE /COMPILE GLXSCN.MAC
@COMPILE /COMPILE GLXTXT.MAC

@DELETE GLXLIB.REL
@APPEND GLXINI.REL,GLXMAC.REL,GLXOTS.REL,GLXCOM.REL,GLXIPC.REL,GLXFIL.REL,GLXTXT.REL,GLXLNK.REL,GLXSCN.REL,GLXKBD.REL,GLXMEM.REL,GLXINT.REL (TO) GLXLIB.REL

;
; Build GLXLIB Object Time System
;

@COPY TTY: GLXPUR.MAC
@GLXPURE==-1
@

@COMPILE /COMPILE GLXPUR.MAC+GLXMAC.MAC
@COMPILE /COMPILE GLXINI.MAC
@COMPILE /COMPILE GLXCOM.MAC
@COMPILE /COMPILE GLXFIL.MAC
@COMPILE /COMPILE GLXINT.MAC
@COMPILE /COMPILE GLXIPC.MAC
@COMPILE /COMPILE GLXKBD.MAC
@COMPILE /COMPILE GLXLNK.MAC
@COMPILE /COMPILE GLXMEM.MAC
@COMPILE /COMPILE GLXOTS.MAC
@COMPILE /COMPILE GLXSCN.MAC
@COMPILE /COMPILE GLXTXT.MAC

LOAD::
@R LINK
*GLXLIB/SAVE = -
*/SET:.HIGH.:400000 /SET:DATA:600000 /SYMSEG:PSECT:.HIGH. /LOCALS -
*GLXMAC, GLXOTS, GLXCOM, GLXIPC, GLXFIL, GLXKBD, -
*GLXLNK, GLXMEM, GLXSCN, GLXTXT, GLXINT, GLXINI -
*/GO

FINI::

@FDIRECT GLXLIB.EXE,GLXLIB.REL
@PLEASE	GLXLIB Assembly Successful
@NOERROR
@MODIFY GALAXY/DEP:-1

%CERR::
%ERR::
@PLEASE	Error During GLXLIB Assembly

END::
%FIN::
