!LPTSPL.CTL
!This Control File Assembles, Loads, and saves LPTSPL
!
!                COPYRIGHT (C) 1979,1980,1981,1982,1984,1987,1988
!                    DIGITAL EQUIPMENT CORPORATION
!
!     THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY  BE  USED
!     AND COPIED ONLY IN ACCORDANCE WITH THE TERMS OF SUCH LICENSE
!     AND WITH THE INCLUSION OF THE ABOVE COPYRIGHT NOTICE.   THIS
!     SOFTWARE  OR ANY OTHER COPIES THEREOF MAY NOT BE PROVIDED OR
!     OTHERWISE MADE AVAILABLE TO ANY OTHER PERSON.  NO  TITLE  TO
!     AND OWNERSHIP OF THE SOFTWARE IS HEREBY TRANSFERRED.
!
!     THE INFORMATION  IN  THIS  SOFTWARE  IS  SUBJECT  TO  CHANGE
!     WITHOUT  NOTICE  AND SHOULD NOT BE CONSTRUED AS A COMMITMENT
!     BY DIGITAL EQUIPMENT CORPORATION.
!
!     DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR RELIABILITY
!     OF  ITS  SOFTWARE  ON  EQUIPMENT  WHICH  IS  NOT SUPPLIED BY
!     DIGITAL.
!

!System Files

!	ACTSYM.UNV
!	MONSYM.UNV	
!	MACSYM.UNV

!Required Files in Your Area

!	GLXMAC.UNV	Library Macro and Symbol Definitions
!	GLXLIB.REL
!	QSRMAC.UNV
!	ORNMAC.UNV
!	D60JSY.REL	DN60 (IBMCOM) INTERFACE ROUTINES
!	D60UNV.UNV	DN60 (IBMCOM) INTERFACE ROUTINES

!Source Files

!	LPTMAC.MAC
!	LISMAC.MAC
!	LPTSPL.MAC
!	LPTCLU.MAC
!	LPTDQS.MAC
!	LPTSUB.MAC
!	LPTUSR.MAC
!	LISSPL.MAC

!Output Files

!	LPTSPL.EXE
!	LISSPL.EXE

!  Set up logical names and such

@TAKE BATCH.CMD

@DEF REL: DSK:
@DEF UNV: DSK:

@VDIR	LPTMAC.MAC
@VDIR	LPTSPL.MAC
@VDIR	LPTCLU.MAC
@VDIR	LPTDQS.MAC
@VDIR	LPTSUB.MAC
@VDIR	LPTUSR.MAC
@VDIR	LISMAC.MAC
@VDIR	LISSPL.MAC

COMP::

@COMPILE/COMPILE LPTMAC.MAC
@COMPILE/COMPILE LISMAC.MAC
@COMPILE/COMPILE LPTUSR.MAC
@COMPILE/COMPILE LPTSPL.MAC
@COMPILE/COMPILE LPTCLU.MAC
@COMPILE/COMPILE LPTDQS.MAC
@COMPILE/COMPILE LPTSUB.MAC
@COMPILE/COMPILE LISSPL.MAC

@R LINK
*/LOCALS/SYMSEG:LOW=LPTSPL,LPTCLU,LPTDQS,LPTSUB,LPTUSR,D60JSY/GO

@SAVE LPTSPL

@R LINK
*/LOCALS/SYMSEG:LOW=LISSPL/GO
@SAVE LISSPL

FINI::
@VDIRECT LPTSPL.EXE

@PLEASE	LPTSPL Assembly Successful

NOERROR
@MODIFY BATCH GALAXY/DEP:-1


%CERR::
%ERR::

@PLEASE	Error During LPTSPL Assembly

%FIN::
