!QUASAR.CTL
!This Control File Assembles, Loads, and saves QUASAR

!                COPYRIGHT (C) 1979,1980,1981,1982,1984,1987,1988
!                    DIGITAL EQUIPMENT CORPORATION
!
!     THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY  BE  USED
!     AND COPIED ONLY IN ACCORDANCE WITH THE TERMS OF SUCH LICENSE
!     AND WITH THE INCLUSION OF THE ABOVE COPYRIGHT NOTICE.   THIS
!     SOFTWARE  OR ANY OTHER COPIES THEREOF MAY NOT BE PROVIDED OR
!     OTHERWISE MADE AVAILABLE TO ANY OTHER PERSON.  NO  TITLE  TO
!     AND OWNERSHIP OF THE SOFTWARE IS HEREBY TRANSFERRED.
!
!     THE INFORMATION  IN  THIS  SOFTWARE  IS  SUBJECT  TO  CHANGE
!     WITHOUT  NOTICE  AND SHOULD NOT BE CONSTRUED AS A COMMITMENT
!     BY DIGITAL EQUIPMENT CORPORATION.
!
!     DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR RELIABILITY
!     OF  ITS  SOFTWARE  ON  EQUIPMENT  WHICH  IS  NOT SUPPLIED BY
!     DIGITAL.

!System Files

!	MONSYM.UNV

!Required Files in Your Area

!	GLXMAC.UNV	Library Macro and Symbol Definitions
!	GLXLIB.REL
!	QSRMAC.UNV
!	ORNMAC.UNV
!	NEBMAC.UNV

!Source Files

!	 QUASAR.MAC
!	 QSRADM.MAC
!	 QSRDSP.MAC
!	 QSRFSS.MAC
!	 QSRIPC.MAC
!	 QSRT20.MAC
!	 QSRMEM.MAC
!	 QSRQUE.MAC
!	 QSRSCH.MAC
!	 QSRNET.MAC
!	 QSRMDA.MAC

!Output Files

!	QUASAR.EXE

@TAKE BATCH.CMD

@DEF REL: DSK:,REL:
@DEF UNV: DSK:,UNV:

@VDIR	 QUASAR.MAC
@VDIR	 QSRADM.MAC
@VDIR	 QSRDSP.MAC
@VDIR	 QSRFSS.MAC
@VDIR	 QSRIPC.MAC
@VDIR	 QSRT20.MAC
@VDIR	 QSRMEM.MAC
@VDIR	 QSRQUE.MAC
@VDIR	 QSRSCH.MAC
@VDIR	 QSRNET.MAC
@VDIR	 QSRMDA.MAC


COMP::

@COMPILE QSRMAC.MAC

@COMPILE/COMPILE QUASAR.MAC
@COMPILE/COMPILE QSRADM.MAC
@COMPILE/COMPILE QSRDSP.MAC
@COMPILE/COMPILE QSRFSS.MAC
@COMPILE/COMPILE QSRIPC.MAC
@COMPILE/COMPILE QSRT20.MAC
@COMPILE/COMPILE QSRMEM.MAC
@COMPILE/COMPILE QSRQUE.MAC
@COMPILE/COMPILE QSRSCH.MAC
@COMPILE/COMPILE QSRNET.MAC
@COMPILE/COMPILE QSRMDA.MAC

LOAD::

@CHKPNT LOAD:
@LOAD QUASAR,QSRMEM,QSRQUE,QSRSCH,QSRMDA,QSRIPC,QSRFSS,QSRADM,QSRDSP,QSRT20,QSRNET
@SAVE QUASAR

@VDIRECT QUASAR.EXE,
@CHECK
@


@PLEASE	QUASAR Assembly Successful
@NOERROR
@MODIFY BATCH GALAXY/DEP:-1

%CERR::
%ERR::

@PLEASE	Error During QUASAR Assembly

%FIN::
