!SPROUT.CTL

!                COPYRIGHT (C) 1979,1980,1981,1982,1984,1987,1988
!                    DIGITAL EQUIPMENT CORPORATION
!
!     THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY  BE  USED
!     AND COPIED ONLY IN ACCORDANCE WITH THE TERMS OF SUCH LICENSE
!     AND WITH THE INCLUSION OF THE ABOVE COPYRIGHT NOTICE.   THIS
!     SOFTWARE  OR ANY OTHER COPIES THEREOF MAY NOT BE PROVIDED OR
!     OTHERWISE MADE AVAILABLE TO ANY OTHER PERSON.  NO  TITLE  TO
!     AND OWNERSHIP OF THE SOFTWARE IS HEREBY TRANSFERRED.
!
!     THE INFORMATION  IN  THIS  SOFTWARE  IS  SUBJECT  TO  CHANGE
!     WITHOUT  NOTICE  AND SHOULD NOT BE CONSTRUED AS A COMMITMENT
!     BY DIGITAL EQUIPMENT CORPORATION.
!
!     DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR RELIABILITY
!     OF  ITS  SOFTWARE  ON  EQUIPMENT  WHICH  IS  NOT SUPPLIED BY
!     DIGITAL.

!This Control File Assembles, Loads, and saves SPROUT

!System Files

!	ACTSYM.UNV
!	MONSYM.UNV

!Required Files in or Your Area

!	GLXMAC.UNV	Library Macro and Symbol Definitions
!	GLXLIB.REL

!Source Files

!	SPROUT.MAC

!Output Files

!	SPROUT.EXE

@TAKE BATCH.CMD

@DEF REL: DSK:
@DEF UNV: DSK:

@VDIR	SPROUT.MAC


COMP::

@COMPILE/COMPILE SPROUT.MAC
@LOAD SPROUT
@SAVE SPROUT

@VDIRECT SPROUT.EXE

@PLEASE	SPROUT Assembly Successful

NOERROR
@MODIFY BATCH GALAXY/DEP:-1


%CERR::
%ERR::

@PLEASE	Error During SPROUT Assembly

%FIN::
