;Command file to copy CMD-EXEC modules
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Command Editor files
COPY FROM-SOURCE:CMDED.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:EXECF3.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:EXECCE.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MKCEXC.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MKCEXC.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MKCEXC.CCL TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:EXEC-ALTER-KEYS.HLP TO-SOURCE:*.*.-1
COPY FROM-SOURCE:EXEC-EMACS-KEYS.HLP TO-SOURCE:*.*.-1
COPY FROM-SOURCE:EXEC-SED-KEYS.HLP TO-SOURCE:*.*.-1
COPY FROM-SOURCE:EXEC-VMS-KEYS.HLP TO-SOURCE:*.*.-1
COPY FROM-SOURCE:EXEC-COMMAND-EDITOR.HLP TO-SOURCE:*.*.-1
COPY FROM-SOURCE:COMMAND-EDITOR-NOTES.TXT TO-SOURCE:*.*.-1

;Final product
COPY FROM-SOURCE:CMD-EXEC.EXE TO-SOURCE:*.*.-1

