;This file is neccessary to assemble the PCL source modules.

EXEC:EXECF2+EXEC:EXECCA EXECC2
;EXEC:EXECPM.MAC EXECPM
;EXEC:EXECPS.MAC EXECPS
;EXEC:EXECPD.B36 EXECPD
;EXEC:EXECPC.B36 EXECPC
;EXEC:EXECPI.B36 EXECPI
;EXEC:EXECPU.B36 EXECPU
;EXEC:EXECPX.B36 EXECPX



