
;Command file to copy PCL-EXEC modules
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;PCL files
COPY FROM-SOURCE:PCL.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:EXECF2.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:EXECPM.REL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:EXECPS.REL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:EXECPI.REL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:EXECPC.REL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:EXECPX.REL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:EXECPU.REL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MKPEXC.CCL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MKPEXC.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:CUST-MKPEXC.CMD TO-SOURCE:MKPEXC.CMD
COPY FROM-SOURCE:MKPEXC.CTL TO-SOURCE:*.*.-1

;Final product
COPY FROM-SOURCE:PCL-EXEC.EXE TO-SOURCE:*.*.-1

