!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING ACTGEN
INFORMATION LOGICAL FROM*:
INFORMATION LOGICAL TO*:

;Files required to build product
COPY FROM-SOURCE:ACTGEN.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ACTGEN.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ACTGEN.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-HLP:ACTGEN.HLP TO-HLP:*.*.-1
COPY FROM-DOC:ACTGEN.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SUBSYS:ACTGEN.EXE TO-SUBSYS:*.*.-1
