!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING ACTSYM
INFORMATION LOGICAL FROM*:
INFORMATION LOGICAL TO*:

;Files required to build product
COPY FROM-SOURCE:ACTSYM.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ACTSYM.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ACTSYM.MAC TO-SOURCE:*.*.-1

;Final product
COPY FROM-SUBSYS:ACTSYM.UNV TO-SUBSYS:*.*.-1
