!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING BOOT

;Files needed to build the product
COPY FROM-SOURCE:BOOT.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:BOOT.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:BOOT.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:PMT.MAC  TO-SRCE:*.*.-1
COPY FROM-SOURCE:RP2.MAC  TO-SRCE:*.*.-1
COPY FROM-SOURCE:DXMCA.ADX TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:DXMCA.RMC TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:DXMCE.ADX TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:DXMCE.RMC TO-SUBSYS:*.*.-1

;Documentation for product
COPY FROM-DOC:BOOT.DOC TO-DOC:*.*.-1
COPY FROM-DOC:BOOT.TCO TO-DOC:*.*.-1

;Final product
COPY FROM-SUBSYS:BOOT.EXB TO-SYSTEM:*.*.-1
COPY FROM-SUBSYS:MTBOOT.EXB TO-SYSTEM:*.*.-1
COPY FROM-SUBSYS:RP2DBT.EXB TO-SYSTEM:*.*.-1
COPY FROM-SUBSYS:RP2MBT.EXB TO-SYSTEM:*.*.-1

