!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING CHKPNT
INFORMATION LOGICAL-NAMES TO-*:
INFORMATION LOGICAL-NAMES FROM-*:

;Files required to build product
COPY FROM-SOURCE:CHKPNT.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:CHKPNT.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:CHKPNT.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ACTSYM.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-HLP:CHKPNT.HLP TO-HLP:*.*.-1
COPY FROM-DOC:CHKPNT.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SUBSYS:CHKPNT.EXE TO-SUBSYS:*.*.-1
