!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING DDT11

;Files required to build product
COPY FROM-SOURCE:DDT11.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DDT11.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DDT11.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DDTSYM.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DDTSIM.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DDTGP.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DDTFIL.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-DOC:DDT11.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SUBSYS:DDT11.EXE TO-SUBSYS:*.*.-1
