!SET TRAP FILE
TAKE BATCH.CMD

DEFINE EDT: UTEDT:
DEFINE EDTEDT: UTEDT:
DEFINE EDTDEB: UTEDT:
DEFINE EDTRUN: UTEDT:
DEFINE EDTDOC: UTEDT:
DEFINE EDTSRC: EDTEDT:,UTEDT:
DEFINE EDTBLD: UTEDT:
DEFINE EDTREL: UTEDT:
DEFINE EDTSYS: EDTREQ:,UTEDT:
DEFINE EDTREQ: EDTEDT:,UTEDT:
DEFINE DSK: DSK:,EDTREL:,EDTREQ:,EDTSRC:,EDTDOC:
DEFINE SYS: DSK:,PKGBLD:[frozen]
DEFINE BLI: SYS:,BLI:

TAKE
