;Command file to copy bundled EXEC modules
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:


;Files required to build product
COPY FROM-SOURCE:EXEC.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MKEXEC.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:EXEC.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:LOEXEC.CCL TO-SOURCE:*.*.-1

;Command module to allow flavors of the EXEC
COPY FROM-SOURCE:EXECDE.UNV TO-SOURCE:*.*.-1
COPY FROM-SOURCE:EXECCA.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:EXECF0.MAC TO-SOURCE:*.*.-1

;All EXEC .rel files except EXECCx(EXECFx+EXECCA) and MIC .rel files
COPY FROM-SOURCE:T20EX7.REL TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:EXEC.DOC TO-DOC:*.*.-1
;COPY FROM-SOURCE:EXEC.BWR TO-DOC:*.*.-1
COPY FROM-SOURCE:EXEC.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:HELP.HLP TO-DOC:*.*.-1
COPY FROM-SOURCE:TERMINAL.HLP TO-DOC:*.*.-1
COPY FROM-SOURCE:HELP.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:TERMINAL.HLP TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SOURCE:EXEC.EXE TO-SYSTEM:*.*.-1
