!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING FE
INFORMATION LOGICAL FROM*:
INFORMATION LOGICAL TO*:

;Files required to build product
COPY FROM-SOURCE:FE.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:FE.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:FE.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-HLP:FE.HLP TO-HLP:*.*.-1
COPY FROM-DOC:FE.DOC TO-DOC:*.*.-1
COPY FROM-DOC:USEFE.MEM TO-DOC:*.*.-1

;Final product
COPY FROM-SUBSYS:FE.EXE TO-SUBSYS:*.*.-1
