;COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING HELPER
INFORMATION LOGICAL FROM*:
INFORMATION LOGICAL TO*:

;Files required to build product
COPY FROM-SOURCE:HELPER.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:HELPER.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:HELPER.MAC TO-SOURCE:*.*.-1

;Final product
COPY FROM-SUBSYS:HELPER.REL TO-SUBSYS:*.*.-1

