!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING INFO
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:INFO.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:INFO.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:INFO.MAC TO-SOURCE:*.*.-1

;Documentation
COPY FROM-DOC:INFO.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SUBSYS:INFO.EXE TO-SUBSYS:*.*.-1
