COPY FROM-SOURCE:CI20.ULD	TO-SOURCE:
COPY FROM-SOURCE:IPAGEN.EXE	TO-SOURCE:
COPY FROM-SOURCE:IPAGEN.MAC	TO-SOURCE:
COPY FROM-SOURCE:IPAGEN.REL	TO-SOURCE:
COPY FROM-SOURCE:IPALOD.CTL	TO-SOURCE:
COPY FROM-SOURCE:IPALOD.CMD	TO-SOURCE:
COPY FROM-SOURCE:IPALOD.EXE	TO-SYSTEM:
