!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING JOBDAT
INFORMATION LOGICAL FROM*:
INFORMATION LOGICAL TO*:

;Files required to build product
COPY FROM-SOURCE:JOBDAT.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:JOBDAT.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:JOBDAT.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-DOC:JOBDAT.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SUBSYS:JOBDAT.REL TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:JOBDAT.UNV TO-SUBSYS:*.*.-1
