;Command file for obtaining all files relevant to building MACRO

INFORMATION LOG TO-*:
INFORMATION LOG FROM-*:

;Source
COPY FROM-SOURCE:MACRO.MAC TO-SOURCE:*.*.-1

;Command files
COPY FROM-SOURCE:MACRO.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MACRO.CTL TO-SOURCE:*.*.-1

;Documentation
COPY FROM-HLP:MACRO.HLP TO-HLP:*.*.-1
COPY FROM-SOURCE:MACRO.BWR TO-SOURCE:*.*.-1
COPY FROM-DOC:MACRO.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SUBSYS:MACRO.EXE TO-SUBSYS:*.*.-1
