!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING MACSYM
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:MACSYM.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MACSYM.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:REL1.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MACSYM.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-DOC:MACSYM.MEM TO-DOC:*.*.-1
COPY FROM-DOC:MACSYM.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SUBSYS:MACREL.REL TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:MACSYM.UNV TO-SUBSYS:*.*.-1

