!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING MACTEN
INFORMATION LOGICAL FROM*:
INFORMATION LOGICAL TO*:

;Files required to build product
COPY FROM-SOURCE:MACTEN.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MACTEN.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MACTEN.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-DOC:MACTEN.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SUBSYS:MACTEN.UNV TO-SUBSYS:*.*.-1

