!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING MAKLIB
INFORMATION LOGICAL FROM*:
INFORMATION LOGICAL TO*:

;Files required to build product
COPY FROM-SOURCE:MAKLIB.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MAKLIB.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MAKLIB.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-HLP:MAKLIB.HLP TO-HLP:*.*.-1
COPY FROM-DOC:MAKLIB.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SUBSYS:MAKLIB.EXE TO-SUBSYS:*.*.-1
