!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING MAPPER
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:MAPPER.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MAPPER.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MAPPER.MAC TO-SOURCE:*.*.-1

;Final product
COPY FROM-SUBSYS:MAPPER.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:PROGRAM-NAME-CACHE.TXT TO-SYSTEM:*.*.-1

