!Copy file, to move everything needed to build MS to a new place
!Demonstrate source and Destination

I LOG FROM-SOURCE:
I LOG TO-SOURCE:
I LOG FROM-EXE:
I LOG FROM-DOC:
I LOG TO-EXE:
I LOG TO-DOC:


EXPUNGE TO-SOURCE:

!Demonstrate existance of files we expect to be on SYS: for a build

VDIR SYS:GLXLIB.*,SYS:GLXINI.*,SYS:MACRO.EXE,SYS:LINK.EXE

!Copy things other than source files

COPY FROM-SOURCE:SETSRC.CMD TO-SOURCE:
COPY FROM-SOURCE:MSCOPY.CMD TO-SOURCE:
COPY FROM-SOURCE:MS.CTL TO-SOURCE:
COPY FROM-SOURCE:MS.CMD TO-SOURCE:
COPY FROM-SUBSYS:MS.EXE TO-SUBSYS:
COPY FROM-SUBSYS:MS.HLP TO-SUBSYS:
COPY FROM-SUBSYS:MSUNV.UNV TO-SUBSYS:

COPY FROM-DOC:MS-MX.BWR TO-DOC:
COPY FROM-DOC:MS-MX.DOC TO-DOC:

COPY FROM-source:MS.HLP TO-source:	

!Copy source files

COPY FROM-SOURCE:ARMAIL.MAC TO-SRCE:MS-ARMAIL.MAC
COPY FROM-SOURCE:ARMAIL.MAC TO-SOURCE:
COPY FROM-SOURCE:MS.MAC TO-SOURCE:
COPY FROM-SOURCE:MSCNFG.MAC TO-SOURCE:
COPY FROM-SOURCE:MSDLVR.MAC TO-SOURCE:
COPY FROM-SOURCE:MSDSPL.MAC TO-SOURCE:
COPY FROM-SOURCE:MSFIL.MAC TO-SOURCE:
COPY FROM-SOURCE:MSGUSR.MAC TO-SOURCE:
COPY FROM-SOURCE:MSHOST.MAC TO-SOURCE:
COPY FROM-SOURCE:MSLCL.MAC TO-SOURCE:
COPY FROM-SOURCE:MSMCMD.MAC TO-SOURCE:
COPY FROM-SOURCE:MSNET.MAC TO-SOURCE:
COPY FROM-SOURCE:MSSEQ.MAC TO-SOURCE:
COPY FROM-SOURCE:MSTXT.MAC TO-SOURCE:
COPY FROM-SOURCE:MSUNV.MAC TO-SOURCE:
COPY FROM-SOURCE:MSUTL.MAC TO-SOURCE:
COPY FROM-SOURCE:MSUUO.MAC TO-SOURCE:
COPY FROM-SOURCE:MSVER.MAC TO-SOURCE:
;REL FILES NEEDED FOR PACKAGING
COPY FROM-SOURCE:MS.REL		TO-SRCE:
COPY FROM-SOURCE:MSCNFG.REL	TO-SRCE:
COPY FROM-SOURCE:MSDLVR.REL	TO-SRCE:
COPY FROM-SOURCE:MSDSPL.REL	TO-SRCE:
COPY FROM-SOURCE:MSFIL.REL	TO-SRCE:
COPY FROM-SOURCE:MSGUSR.REL	TO-SRCE:
COPY FROM-SOURCE:MSHOST.REL	TO-SRCE:
COPY FROM-SOURCE:MSLCL.REL	TO-SRCE:
COPY FROM-SOURCE:MSMCMD.REL	TO-SRCE:
COPY FROM-SOURCE:MSNET.REL	TO-SRCE:
COPY FROM-SOURCE:MSSEQ.REL	TO-SRCE:
COPY FROM-SOURCE:MSTXT.REL	TO-SRCE:
COPY FROM-SOURCE:MSUNV.REL	TO-SRCE:
COPY FROM-SOURCE:MSUTL.REL	TO-SRCE:
COPY FROM-SOURCE:MSUUO.REL	TO-SRCE:
COPY FROM-SOURCE:MSVER.REL	TO-SRCE:
EXPUNGE TO-SOURCE:
