!Copy file, to move everything needed to build MS to a new place
!Demonstrate source and Destination

I LOG FROM-SOURCE:
I LOG TO-SOURCE:
I LOG FROM-EXE:
I LOG FROM-DOC:
I LOG TO-EXE:
I LOG TO-DOC:


EXPUNGE TO-SOURCE:

!Demonstrate existance of files we expect to be on SYS: for a build

VDIR SYS:GLXLIB.*,SYS:GLXINI.*,SYS:MACRO.EXE,SYS:LINK.EXE

!Copy things other than source files

COPY FROM-SOURCE:SETSRC.CMD TO-SOURCE:
COPY FROM-SOURCE:MSCOPY.CMD TO-SOURCE:
COPY FROM-SOURCE:MS.CTL TO-SOURCE:

COPY FROM-DOC:MS-MX.BWR TO-DOC:
COPY FROM-DOC:MS-MX.DOC TO-DOC:

COPY FROM-EXE:MS.HLP TO-EXE:	

!Copy source files

COPY FROM-SOURCE:ARMAIL.MAC TO-SOURCE:
COPY FROM-SOURCE:MS.MAC TO-SOURCE:
COPY FROM-SOURCE:MSCNFG.MAC TO-SOURCE:
COPY FROM-SOURCE:MSDLVR.MAC TO-SOURCE:
COPY FROM-SOURCE:MSDSPL.MAC TO-SOURCE:
COPY FROM-SOURCE:MSFIL.MAC TO-SOURCE:
COPY FROM-SOURCE:MSGUSR.MAC TO-SOURCE:
COPY FROM-SOURCE:MSHOST.MAC TO-SOURCE:
COPY FROM-SOURCE:MSLCL.MAC TO-SOURCE:
COPY FROM-SOURCE:MSMCMD.MAC TO-SOURCE:
COPY FROM-SOURCE:MSNET.MAC TO-SOURCE:
COPY FROM-SOURCE:MSSEQ.MAC TO-SOURCE:
COPY FROM-SOURCE:MSTXT.MAC TO-SOURCE:
COPY FROM-SOURCE:MSUNV.MAC TO-SOURCE:
COPY FROM-SOURCE:MSUTL.MAC TO-SOURCE:
COPY FROM-SOURCE:MSUUO.MAC TO-SOURCE:
COPY FROM-SOURCE:MSVER.MAC TO-SOURCE:
EXPUNGE TO-SOURCE:
