!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING PAT AND PA1050
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:PAT.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:PAT.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:PAT.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-DOC:PAT.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SUBSYS:PAT.EXE TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:PA1050.EXE TO-SUBSYS:*.*.-1
