!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING RSXFMT
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:RSXFMT.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:RSXFMT.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:RSXFMT.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-HLP:RSXFMT.HLP TO-HLP:*.*.-1
COPY FROM-DOC:RSXFMT.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SUBSYS:RSXFMT.EXE TO-SUBSYS:*.*.-1
