UNIVERSAL RTLDYN -- RTL library definition

;
;	COPYRIGHT (C) DIGITAL EQUIPMENT CORPORATION 1984, 1986.
;	ALL RIGHTS RESERVED.
;
;	THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY  BE  USED  AND
;	COPIED ONLY IN ACCORDANCE WITH THE TERMS OF SUCH LICENSE AND WITH
;	THE INCLUSION OF THE ABOVE COPYRIGHT NOTICE.   THIS  SOFTWARE  OR
;	ANY  OTHER  COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE
;	AVAILABLE TO ANY OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE
;	SOFTWARE IS HEREBY TRANSFERRED.
;
;	THE INFORMATION IN THIS SOFTWARE IS  SUBJECT  TO  CHANGE  WITHOUT
;	NOTICE  AND  SHOULD  NOT  BE CONSTRUED AS A COMMITMENT BY DIGITAL
;	EQUIPMENT CORPORATION.
;
;	DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR  RELIABILITY  OF
;	ITS SOFTWARE ON EQUIPMENT THAT IS NOT SUPPLIED BY DIGITAL.
;

SUBTTL Edit History

; Version 1.0

; Version 1.1

;.EDIT 50	Formally go to version 1.1, update copyright, insert V1.1
;			development changes (formally V2)
;		DDB,15-Jan-85,SPR:NONE
;.EDIT 51	Add GLOBbing in build procedure, make DY$CBK work from JCK.
;		DDB,30-Apr-85,SPR:NONE
;.EDIT 55	Add RL$2BG -- convert two-word byte-pointer to OWG.
;		DDB,10-JUN-85,SPR:NONE

SEARCH DDBSYM,DYNSYM

SALL

$LIBDEF (RTL,RL,$RTL,DYN%VE,VM%MIG,"DYNLIB$RTL%","SYS:RTL.EXE",
<RL$MIN>,
<DY$BS,DY$DYN
,<ABS.,,,$FC>,<ACOS.,,,$FC>,<AIMAG.,,,$FC>,<AINT.,,,$FC>,<ALG10.,,,$FC>,<ALOG.,,,$FC>,<AMAX0.,,,$FC>,<AMAX1.,,,$FC>,<AMIN0.,,,$FC>,<AMIN1.,,,$FC>
,<AMOD.,,,$FC>,<ANINT.,,,$FC>,<ASIN.,,,$FC>,<ATAN.,,,$FC>,<ATAN2.,,,$FC>,<CABS.,,,$FC>,<CCOS.,,,$FC>,<CDABS.,,,$FC>,<CDCOS.,,,$FC>,<CDLOG,,,$FC>,<CDSIN.,,,$FC>
,<CDSQT.,,,$FC>,<CEXP.,,,$FC>,<CEXP2.,,,$FC>,<CEXP3.,,,$FC>,<CGABS.,,,$FC>,<CGCOS.,,,$FC>,<CGEXP.,,,$FC>,<CGLOG.,,,$FC>
,<CGSIN.,,,$FC>,<CGSQT.,,,$FC>,<CLOG.,,,$FC>,<CMPL.C.,,,$FC>,<CMPL.D.,,,$FC>,<CMPL.G.,,,$FC>,<CMPL.I.,,,$FC>,<CMPLX.,,,$FC>,<CONJG.,,,$FC>,<COS.,,,$FC>
,<COSD.,,,$FC>,<COSH.,,,$FC>,<COTAN.,,,$FC>,<CSIN.,,,$FC>,<CSQRT.,,,$FC>,<DABS.,,,$FC>,<DACOS.,,,$FC>,<DASIN.,,,$FC>,<DATAN.,,,$FC>,<DATN2.,,,$FC>
,<DBLE.,,,$FC>,<DCOS.,,,$FC>,<DCOSH.,,,$FC>,<DCOTN.,,,$FC>,<DDIM.,,,$FC>,<DEXP.,,,$FC>,<DEXP2.,,,$FC>,<DEXP3.,,,$FC>,<DFLOT.,,,$FC>,<DIM.,,,$FC>
,<DINT.,,,$FC>,<DLG10.,,,$FC>,<DLOG.,,,$FC>,<DMAX1.,,,$FC>,<DMIN1.,,,$FC>,<DMOD.,,,$FC>,<DNINT.,,,$FC>,<DPROD.,,,$FC>,<DSIGN.,,,$FC>,<DSIN.,,,$FC>
,<DSINH.,,,$FC>,<DSQRT.,,,$FC>,<DTAN.,,,$FC>,<DTANH.,,,$FC>,<DTOG,,,$FC>,<DTOGA,,,$FC>,DY$LER,DY$LOD
,DY$MIN,<EXP.,,,$FC>,<EXP1.,,,$FC>,<EXP2.,,,$FC>,<EXP3.,,,$FC>,<FLOAT.,,,$FC>,<GACOS.,,,$FC>,<GASIN.,,,$FC>,<GATAN.,,,$FC>,<GATN2.,,,$FC>
,<GCOS.,,,$FC>,<GCOSH.,,,$FC>,<GCOTN.,,,$FC>,<GDIM.,,,$FC>,<GEXP.,,,$FC>,<GEXP2.,,,$FC>,<GEXP3.,,,$FC>,<GINT.,,,$FC>,<GLG10.,,,$FC>,<GLOG.,,,$FC>
,<GMOD.,,,$FC>,<GNINT.,,,$FC>,<GPROD.,,,$FC>,<GSIN.,,,$FC>,<GSINH.,,,$FC>,<GSQRT.,,,$FC>,<GTAN.,,,$FC>,<GTANH.,,,$FC>,<GTOD,,,$FC>,<GTODA,,,$FC>
,<IABS.,,,$FC>,<IDIM.,,,$FC>,<IDINT.,,,$FC>,<IDNIN.,,,$FC>,<IFIX.,,,$FC>,<IGNIN.,,,$FC>,<INT.,,,$FC>,<ISIGN.,,,$FC>,<MAX0.,,,$FC>,<MAX1.,,,$FC>
,ME$ALM,ME$ALP,ME$ALS,<ME$DLM,,,$AR (1)>,ME$DLP,ME$DLS,ME$DMC,<ME$MEM,,,$AR <1,2>>,<MIN0.,,,$FC>,<MIN1.,,,$FC>
,<MOD.,,,$FC>,<NINT.,,,$FC>,<RAN,,,$FC>,<RANS,,,$FC>,RL$FAO,<SAVRAN,,,$FC>,<SETRAN,,,$FC>,SG$ALC,SG$DIC,SG$DLC
,SG$DLG,SG$DMG,SG$EIC,SG$EST,SG$LES,SG$LRM,SG$PEM,SG$REM,SG$SEC,SG$SIG
,<SIGN.,,,$FC>,<SIN.,,,$FC>,<SIND.,,,$FC>,<SINH.,,,$FC>,<SNGL.,,,$FC>,<SQRT.,,,$FC>,<TAN.,,,$FC>,<TANH.,,,$FC>
,SG$NAS,DY$CBK,RL$LBG,RL$NUL,RL$2BG>,
,<SG.ENS,SG.LEV,SG.PFX,SG.SFX,SG.DPX,SG.DSX,SG.OUT,SG.NAS,DY.ZMP>)

; NOTE: DY$BS must occupy position .RLBOO in the CTVEC for the RTL
;       DY$DYN must occupy position .RLDYN in the CTVEC for the RTL
; [51]	RL$NUL must occupy position .RLNUL in the CTVEC for the RTL

END
