;COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING SCAN
INFORMATION LOGICAL FROM*:
INFORMATION LOGICAL TO*:

;Files required to build product
COPY FROM-SOURCE:SCAN.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SCAN.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SCAN.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SCNMAC.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-DOC:SCAN.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SUBSYS:SCAN.REL TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:SCNMAC.UNV TO-SUBSYS:*.*.-1
