!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING SETSPD
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:SETSPD.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SETSPD.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SETSPD.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-DOC:SETSPD.TCO TO-DOC:*.*.-1
COPY FROM-DOC:SETSPD.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SOURCE:7-SETSPD.EXE TO-SYSTEM:*.*.-1

