!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING SYSJOB
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:SYSJOB.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SYSJOB.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SYSJOB.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SYSTEM.CMD TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-DOC:SYSJOB.TCO TO-DOC:*.*.-1
COPY FROM-DOC:SYSJOB.DOC TO-DOC:*.*.-1
COPY FROM-HLP:SYSJOB.HLP TO-HLP:*.*.-1
COPY FROM-HLP:SYSJOB.HLP TO-SYSTEM:*.*.-1

;Final product
COPY FROM-SOURCE:7-SYSJOB.EXE TO-SYSTEM:*.*.-1
COPY FROM-SOURCE:7-SYSJOB.RUN TO-SRCE:*.*.-1
COPY FROM-SOURCE:7-SYSJOB.RUN TO-SYSTEM:*.*.-1
COPY FROM-SOURCE:7-SYSJOB.RUN TO-TCPSYS:*.*.-1
COPY FROM-SOURCE:SYSTEM.CMD TO-SRCE:*.*.-1
COPY FROM-SOURCE:SYSTEM.CMD TO-SYSTEM:*.*.-1
