!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO TV
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:TV.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:TV.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:TV.MAC TO-SOURCE:*.*.-1

;Documentation for product

;Final product
COPY FROM-SOURCE:TV.EXE TO-SUBSYS:*.*.-1
