!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO ULIST
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:ULIST.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ULIST.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ULIST.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-DOC:ULIST.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SOURCE:ULIST.EXE TO-SUBSYS:*.*.-1
COPY FROM-HLP:ULIST.HLP TO-HLP:*.*.-1
