;COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING WILD
INFORMATION LOGICAL FROM*:
INFORMATION LOGICAL TO*:

;Files required to build product
COPY FROM-SOURCE:WILD.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:WILD.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:WILD.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-DOC:WILD.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SUBSYS:WILD.REL TO-SUBSYS:*.*.-1
