; UPD ID= 8475, RIP:<7.MONITOR>APPARP.CMD.9,   9-Feb-88 11:48:31 by GSCOTT
;TCO 7.1218 - Update copyright notice.
; UPD ID= 8385, RIP:<7.MONITOR>APPARP.CMD.8,  27-Jan-88 10:28:44 by GSCOTT
;TCO 7.1200 - Add JSYSM
;RIP:<7.MONITOR>APPARP.CMD.7 22-Jan-88 11:24:58, Edit by GSCOTT
;TCO 7.1195 - Create as file to produce T20AN.REL from discrete .REL files

;	COPYRIGHT (c) DIGITAL EQUIPMENT CORPORATION 1988.
;	ALL RIGHTS RESERVED.
;
;	THIS SOFTWARE IS FURNISHED UNDER A  LICENSE AND MAY BE USED AND  COPIED
;	ONLY IN  ACCORDANCE  WITH  THE  TERMS OF  SUCH  LICENSE  AND  WITH  THE
;	INCLUSION OF THE ABOVE  COPYRIGHT NOTICE.  THIS  SOFTWARE OR ANY  OTHER
;	COPIES THEREOF MAY NOT BE PROVIDED  OR OTHERWISE MADE AVAILABLE TO  ANY
;	OTHER PERSON.  NO  TITLE TO  AND OWNERSHIP  OF THE  SOFTWARE IS  HEREBY
;	TRANSFERRED.
;
;	THE INFORMATION IN THIS  SOFTWARE IS SUBJECT  TO CHANGE WITHOUT  NOTICE
;	AND SHOULD  NOT  BE CONSTRUED  AS  A COMMITMENT  BY  DIGITAL  EQUIPMENT
;	CORPORATION.
;
;	DIGITAL ASSUMES NO  RESPONSIBILITY FOR  THE USE OR  RELIABILITY OF  ITS
;	SOFTWARE ON EQUIPMENT THAT IS NOT SUPPLIED BY DIGITAL.


DELETE R:T20AN.REL
APPEND R:SCAMPI.REL,R:SCSJSY.REL R:T20AN.REL
APPEND R:PHYMSC.REL,R:PHYMVR.REL,R:PHYKLP.REL R:T20AN.REL
APPEND R:CFSSRV.REL,R:CFSUSR.REL R:T20AN.REL
APPEND R:ENQSRV.REL,R:APRSRV.REL,R:SCHED.REL R:T20AN.REL
APPEND R:PAGEM.REL,R:PAGUTL.REL,R:FORK.REL R:T20AN.REL	;[7.1200]
APPEND R:MEXEC.REL,R:JSYSM.REL,R:GETSAV.REL R:T20AN.REL	;[7.1200]
APPEND R:SYSERR.REL,R:COMND.REL R:T20AN.REL
APPEND R:DEVICE.REL,R:DIRECT.REL,R:ENQ.REL,R:FREE.REL R:T20AN.REL
APPEND R:FUTILI.REL,R:GTJFN.REL,R:IO.REL,R:IPCF.REL R:T20AN.REL
APPEND R:JSYSA.REL,R:JSYSF.REL,R:LOGNAM.REL R:T20AN.REL
APPEND R:LOOKUP.REL,R:MSTR.REL,R:SWPALC.REL,R:DISC.REL R:T20AN.REL
APPEND R:FILINI.REL,R:FILMSC.REL R:T20AN.REL
APPEND R:MFLIN.REL,R:MFLOUT.REL,R:DATIME.REL R:T20AN.REL
APPEND R:PHYSIO.REL,R:DIAG.REL,R:DSKALC.REL R:T20AN.REL
APPEND R:PHYH2.REL,R:PHYP4.REL,R:PHYP2.REL,R:PHYM78.REL R:T20AN.REL
APPEND R:PHYX2.REL,R:PHYM2.REL R:T20AN.REL
APPEND R:TTYSRV.REL,R:NRTSRV.REL,R:RSXSRV.REL R:T20AN.REL
APPEND R:FESRV.REL,R:MAGTAP.REL,R:TAPE.REL,R:TIMER.REL R:T20AN.REL
APPEND R:DTESRV.REL,R:LINEPR.REL,R:CDPSRV.REL,R:PLT.REL R:T20AN.REL
APPEND R:PTP.REL,R:PTR.REL,R:CDRSRV.REL R:T20AN.REL
APPEND R:FILNFT.REL,R:CIDLL.REL,R:CTHSRV.REL,R:D36COM.REL R:T20AN.REL
APPEND R:DNADLL.REL,R:JNTMAN.REL R:T20AN.REL
APPEND R:LLINKS.REL,R:LLMOP.REL,R:NISRV.REL,R:NIUSR.REL R:T20AN.REL
APPEND R:NTMAN.REL,R:ROUTER.REL,R:SCJSYS.REL,R:SCLINK.REL R:T20AN.REL
APPEND R:LATSRV.REL R:T20AN.REL
APPEND R:IPIPIP.REL,R:IPFREE.REL,R:IMPDV.REL,R:IPCIDV.REL R:T20AN.REL
APPEND R:IPNIDV.REL,R:IMPANX.REL,R:MNETDV.REL R:T20AN.REL
APPEND R:TCPTCP.REL,R:TCPCRC.REL,R:TCPJFN.REL,R:TCPBBN.REL R:T20AN.REL
APPEND R:TVTSRV.REL,R:CRYPT.REL,R:DOB.REL R:T20AN.REL
APPEND R:CLUDGR.REL,R:CLUFRK.REL,R:POSTLD.REL R:T20AN.REL
