;  Command file used to copy the TCP Monitor sources.

INFORMATION LOGICAL FROM*:
INFORMATION LOGICAL TO*:

;  Copy the files needed to build the monitor
COPY FROM-SOURCE:ARPA.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ARPSRC.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:T20-AN70.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ASEMBL.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:APPARP.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:PARBIG.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:PARMAX.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:PARDCN.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:PARARP.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:LNKBIG.CCL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:LNKMAX.CCL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:LNKDCN.CCL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:LNKARP.CCL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:LNKANI.CCL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ANNBIG.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ANPBIG.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ANNMAX.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ANPMAX.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ANNDCN.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ANPDCN.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:NAMAN.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:PARAN.MAC TO-SOURCE:*.*.-1

;  Copy the source files 
COPY FROM-SOURCE:ANAUNV.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:IPIPIP.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:IPCIDV.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:IPNIDV.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:IPFREE.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:TCPTCP.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:TCPCRC.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:TCPBBN.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:TCPJFN.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MNETDV.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:IMPANX.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:IMPDV.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:TVTSRV.MAC TO-SOURCE:*.*.-1

